apiVersion: skaffold/v1
kind: Config
metadata:
  name: dashboard-aggregator
deploy:
  kubectl:
    manifests:
      - k8s/dashboard-aggregator.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: discoenv/dashboard-aggregator
  local: {}
