listen_port: 3000

db:
  uri: insert-db-uri-here

logging:
  level: info
  label: dashboard-aggregator

permissions:
  uri: http://permissions
  public_group: put-group-uuid-here

website:
  url: https://cyverse.org
  feeds:
    news: "/news/rss.xml"
  
