listen_port: 3000

db:
    uri: insert-db-uri-here

logging:
    level: info
    label: dashboard-aggregator

permissions:
    uri: http://permissions
    public_group: put-group-uuid-here

website:
    url: https://cyverse.org
    feeds:
        news: "/news/rss.xml"
        events: "/events/rss.xml"

videos:
    url: https://www.youtube.com/feeds/videos.xml?channel_id=UC-gvdjTz9rq6RovZ57LoDDA

apps:
    favorites_group_index: 1
